# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

## Site settings
title:
  en: David CHEN | Sylvia's husband,the father of adorable twins.
  es: David CHEN | Sylvia's husband,the father of adorable twins.
  pl: David CHEN | Sylvia's husband,the father of adorable twins.
  ru: David CHEN | Sylvia's husband,the father of adorable twins.
  zh: David CHEN | Sylvia's husband,the father of adorable twins.
description:
  en: This site is an online communication navigator designed for sharing the latest learning methods and experiences.
  es: This site is an online communication navigator designed for sharing the latest learning methods and experiences.
  pl: This site is an online communication navigator designed for sharing the latest learning methods and experiences.
  ru: This site is an online communication navigator designed for sharing the latest learning methods and experiences.
  zh: 本站致力于分享最新的在线学习方法和经验

index:
  en:
  es: index-es.html
  pl: index-pl.html
  ru: index-ru.html
  zh: index-zh.html
url: "https://davidnsw.github.io/cover/index.html" # the base hostname & protocol for your site
twitter_username: davidnsw
github_username: davidnsw
# feed:
#  en: /feed.xml
#  es: /feed_es.xml
# baseurl: "/pages" # the subpath of your site, e.g. /blog
# email: your-email@domain.com

## Header

technologymenu:
  en: Technology
  es: Tecnología
  pl: Technologia
  ru: Technology
  zh: 技术分享
helpmenu:
  en: Help and Tools
  es: Ayuda y Herramientas
  pl: Pomoc i narzędzia
  ru: Help and Tools
  zh: 工具分享
downloadmenu:
  en: Downloads
  es: Bajar
  pl: Pobierz
  ru: Downloads
  zh: 下载
communitymenu:
  en: Participate
  es: Participar
  pl: Weź udział
  ru: Participate
  zh: 在线交流
languagemenu:
  en: Languages
  es: Idiomas
  pl: Języki
  ru: Languages
  zh: 语言
mastheadtitle:
  en: The Next Generation of Self-learning
  es: The Next Generation of Self-learning
  pl: The Next Generation of Self-learning
  ru: The Next Generation of Self-learning
  zh: 新一代人的自我学习
mastheadtext:
  en: “Life is like riding a bicycle. To keep your balance, you must keep moving.”--Albert Einstein
  es: “Life is like riding a bicycle. To keep your balance, you must keep moving.”--Albert Einstein
  pl: “Life is like riding a bicycle. To keep your balance, you must keep moving.”--Albert Einstein
  ru: “Life is like riding a bicycle. To keep your balance, you must keep moving.”--Albert Einstein
  zh: 人生就像骑自行车，要保持平衡就要不断前进。——爱因斯坦
languagestring:
  en: English
  es: Español
  pl: Polski
  ru: Русский
  zh: 中文

# Updateables

exchanges:
#  - name: Nova Exchange - they closed their business on October 7, 2019
#    url: "https://novaexchange.com"
  - name: Homepage
    url: "https://davidnsw.github.io/home/"
#  - name: CoinsMarket # currently offline - probably scam exchange
#    url: "https://coinsmarkets.com"
#  - name: CoinHouse # with problems, removed until solved - market removed
#    url: "https://coinhouse.eu"

wallets:
  - name: Windows
    url: "https://github.com/davidnsw"
    logo: /assets/windows.svg
  - name: macOS
    url: "https://github.com/davidnsw"
    logo: /assets/mac.svg
  - name: "Ubuntu"
    url: "https://github.com/davidnsw"
    logo: /assets/ubuntu.svg
  - name: "ARM"
    url: "https://github.com/davidnsw"
    logo: /assets/raspberry.svg
  - name: "Source Code"
    url: "https://github.com/davidnsw"
    logo: /assets/git.svg

walletname: Simcoin-QT 0.5.1

# Footer

footertitle:
  en: Use & Participate
  es: Usar & Participar
  pl: Użycie i przystąpienie
  ru: Использование и участие
  zh: 使用和参加
resourcesheading:
  en: Resources
  es: Recursos
  pl: Źródła
  ru: Ресурсы
  zh: 资源链接
socialheading:
  en: Social media
  es: Medios sociales
  pl: Media społecznościowe
  ru: Социальные медиа
  zh: 社交媒体
toolsheading:
  en: Tools
  es: Herramientas
  pl: Narzędzia
  ru: Инструменты
  zh: 工具

# Build settings
markdown: kramdown
